#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dygraphs dyAnnotation
#' @importFrom dygraphs dyAxis
#' @importFrom dygraphs dygraph
#' @importFrom dygraphs dyRangeSelector
#' @importFrom dygraphs dySeries
#' @importFrom dygraphs dyShading
#' @importFrom graphics abline
#' @importFrom graphics axis
#' @importFrom graphics grid
#' @importFrom graphics legend
#' @importFrom graphics lines
#' @importFrom graphics mtext
#' @importFrom graphics par
#' @importFrom graphics plot
#' @importFrom graphics points
#' @importFrom graphics polygon
#' @importFrom graphics strheight
#' @importFrom graphics strwidth
#' @importFrom graphics text
#' @importFrom graphics title
#' @importFrom grDevices extendrange
#' @importFrom lattice barchart
#' @importFrom lattice panel.barchart
#' @importFrom latticeExtra layer
#' @importFrom lmom cdfexp
#' @importFrom lmom cdfgam
#' @importFrom lmom cdfgev
#' @importFrom lmom cdfglo
#' @importFrom lmom cdfgno
#' @importFrom lmom cdfgpa
#' @importFrom lmom cdfgum
#' @importFrom lmom cdfkap
#' @importFrom lmom cdfln3
#' @importFrom lmom cdfnor
#' @importFrom lmom cdfpe3
#' @importFrom lmom cdfwak
#' @importFrom lmom cdfwei
#' @importFrom lmom evplot
#' @importFrom lmom lmrd
#' @importFrom lmom pelexp
#' @importFrom lmom pelgam
#' @importFrom lmom pelgev
#' @importFrom lmom pelglo
#' @importFrom lmom pelgno
#' @importFrom lmom pelgpa
#' @importFrom lmom pelgum
#' @importFrom lmom pelkap
#' @importFrom lmom pelln3
#' @importFrom lmom pelnor
#' @importFrom lmom pelpe3
#' @importFrom lmom pelwak
#' @importFrom lmom pelwei
#' @importFrom lmom quaexp
#' @importFrom lmom quagam
#' @importFrom lmom quagev
#' @importFrom lmom quaglo
#' @importFrom lmom quagno
#' @importFrom lmom quagpa
#' @importFrom lmom quagum
#' @importFrom lmom quakap
#' @importFrom lmom qualn3
#' @importFrom lmom quanor
#' @importFrom lmom quape3
#' @importFrom lmom quawak
#' @importFrom lmom quawei
#' @importFrom lmom samlmu
#' @importFrom lmomRFA regfit
#' @importFrom lmomRFA regquant
#' @importFrom lmomRFA regsamlmu
#' @importFrom lmomRFA sitequant
#' @importFrom plyr rbind.fill.matrix
#' @importFrom scales fullseq
#' @importFrom stats aggregate
#' @importFrom stats approx
#' @importFrom stats coef
#' @importFrom stats embed
#' @importFrom stats filter
#' @importFrom stats ks.test
#' @importFrom stats lm
#' @importFrom stats na.exclude
#' @importFrom stats na.omit
#' @importFrom stats qnorm
#' @importFrom stats quantile
#' @importFrom stats reorder
#' @importFrom stats time
#' @importFrom stats weighted.mean
#' @importFrom utils head
#' @importFrom utils read.table
#' @importFrom utils str
#' @importFrom utils tail
#' @importFrom xts as.xts
#' @importFrom xts is.xts
#' @importFrom xts xtsAttributes
#' @importFrom xts xtsAttributes<-
#' @importFrom zoo coredata
#' @importFrom zoo is.zoo
#' @importFrom zoo zoo
## usethis namespace: end
NULL
